---
- hosts: HomeLab
  become: true
  tasks:
    - name: Check if Python is installed
      raw: command -v python || command -v python3 || echo 'No Python installed'
      register: python_check

    - name: Fail if Python is not installed
      fail:
        msg: "Python is not installed on the target server. Please install Python."
      when: "python_check.stdout == 'No Python installed'"
