---
- name: Reboot Ubuntu Server
  hosts: your_ubuntu_server
  become: yes  # Run tasks with sudo

  tasks:
    - name: Reboot the server
      command: shutdown -r now
      async: 0
      poll: 0
      ignore_errors: true

    - name: Wait for the server to come back
      async_status:
        jid: "{{ ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 30
      delay: 10
